on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.5.x
      - run: npm install --no-audit
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
      - run: npm run package
      - run: tar cf out.tar out
      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: out.tar
          retention-days: 1